name: Rocq Ditto CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        rocq-version: ["9.1.0", "9.0.0", "8.20.0"]
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install opam
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y opam
          else
            brew install opam
          fi
          opam init -y --bare

      - name: Configure Rocq-ditto
        run: |
          set -eux
          ./configure.sh ${{ matrix.rocq-version }}
          eval "$(opam env --switch=./ --set-switch)"

      - name: Build Rocq-ditto
        run: |
          eval "$(opam env --switch=./ --set-switch)"
          dune build

